#!/usr/bin/env bash
# This script displays a story for each user from /etc/passwd

while IFS=: read -r username _ uid gid _ home shell; do
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode PASSWORD, more info about the user here: $uid INFO"
done < /etc/passwd
