#!/usr/bin/env bash
# Display passwd file story

while IFS=: read -r username password uid gid full home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode PASSWORD, more info about the user here: $uid INFO"
done < /etc/passwd

