#!/usr/bin/env bash
# 14-dig_the-data

# Extract IP ($1) and HTTP code ($9), count occurrences, print and sort descending
awk '{print $1, $9}' apache-access.log | awk '{count[$0]++} END {for (k in count) print count[k], k}' | sort -nr
