#!/usr/bin/env bash
# 14-dig_the-data
# Group visitors by IP and HTTP status code, sorted by occurrences

awk '{count[$1" "$9]++} END {for (key in count) print count[key], key}' apache-access.log | sort -nr

