#!/usr/bin/env bash
# Bu skript PID faylı yaradır, sonsuz dövrdə mesaj yazır
# və müxtəlif siqnallara fərqli mesajlarla cavab verir.
PID_FILE="/var/run/myscript.pid"
trap 'echo "I hate the kill command"; rm -f "$PID_FILE"; exit' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
trap 'rm -f "$PID_FILE"; exit' SIGQUIT
pgrep -f "./10-process-and-pid-file"
echo "To infinity and beyond"
sleep 1
done
