#!/usr/bin/env bash
# Init script for manage_my_process

PID_FILE="/var/run/my_process.pid"
PROCESS="./manage_my_process"

case "$1" in
  start)
    # Start the process
    $PROCESS &
    echo $! > "$PID_FILE"
    echo "manage_my_process started"
    ;;
  
  stop)
    if [ -f "$PID_FILE" ]; then
        kill "$(cat $PID_FILE)"
        rm -f "$PID_FILE"
    fi
    echo "manage_my_process is not running"
    
    ;;
  
  restart)
    if [ -f "$PID_FILE" ]; then
        kill "$(cat $PID_FILE)"
        rm -f "$PID_FILE"
    fi
    $PROCESS &
    echo $! > "$PID_FILE"
    echo "manage_my_process restarted"
    ;;
  
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
